//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KriptografskiUredajiSaveznika
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uredajiEntities1 : DbContext
    {
        public uredajiEntities1()
            : base("name=uredajiEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<poruke> porukes { get; set; }
        public virtual DbSet<typex> typexes { get; set; }
        public virtual DbSet<pravila> pravilas { get; set; }
    }
}
