//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KriptografskiUredajiSaveznika
{
    using System;
    using System.Collections.Generic;
    
    public partial class poruke
    {
        public int id { get; set; }
        public string sifrirano { get; set; }
        public string desifrirano { get; set; }
        public string konacno { get; set; }
        public string sifriranoSigaba { get; set; }
        public string greska { get; set; }
    }
}
