//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KriptografskiUredajiSaveznika
{
    using System;
    using System.Collections.Generic;
    
    public partial class typex
    {
        public int id { get; set; }
        public string slovo { get; set; }
        public string sifra { get; set; }
        public string sigabaSifra { get; set; }
    }
}
