//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewsMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string ContactName { get; set; }
        public string Issue { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> IsAnswered { get; set; }
    }
}
