//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReviewsMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class userStoryDEV
    {
        public int Id { get; set; }
        public string FullName { get; set; }
        public string KickstarterCamp { get; set; }
        public string OrderDate { get; set; }
        public string PledgedAmount { get; set; }
        public string OrderNumber { get; set; }
        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public string ImageExt { get; set; }
        public string YourStory { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public Nullable<bool> IsShared { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string BackerNumber { get; set; }
    }
}
