//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoAmI_PC
{
    using System;
    using System.Collections.Generic;
    
    public partial class answer
    {
        public answer()
        {
            this.journals = new HashSet<journal>();
        }
    
        public int id { get; set; }
        public string question { get; set; }
        public string answ1 { get; set; }
        public string answ2 { get; set; }
        public string answ3 { get; set; }
        public Nullable<int> idLevels { get; set; }
        public Nullable<int> idStages { get; set; }
        public Nullable<int> critical { get; set; }
        public Nullable<int> stagesDif { get; set; }
    
        public virtual Level Level { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual ICollection<journal> journals { get; set; }
    }
}
