//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoAmI_PC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Character
    {
        public Character()
        {
            this.journals = new HashSet<journal>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> idLevels { get; set; }
        public Nullable<int> idStages { get; set; }
        public string idPlayers { get; set; }
        public Nullable<int> idCriticals { get; set; }
        public Nullable<int> intro { get; set; }
    
        public virtual Critical Critical { get; set; }
        public virtual Level Level { get; set; }
        public virtual player player { get; set; }
        public virtual Stage Stage { get; set; }
        public virtual ICollection<journal> journals { get; set; }
    }
}
