//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoAmI_PC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Critical
    {
        public Critical()
        {
            this.Characters = new HashSet<Character>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> Choise { get; set; }
        public Nullable<int> idLevel { get; set; }
        public Nullable<int> idStage { get; set; }
    
        public virtual ICollection<Character> Characters { get; set; }
        public virtual Level Level { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
