//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoAmI_PC
{
    using System;
    using System.Collections.Generic;
    
    public partial class journal
    {
        public int id { get; set; }
        public Nullable<int> idLevels { get; set; }
        public Nullable<int> idStages { get; set; }
        public Nullable<int> idAnswers { get; set; }
        public Nullable<int> idCharacters { get; set; }
    
        public virtual answer answer { get; set; }
        public virtual Character Character { get; set; }
        public virtual Level Level { get; set; }
        public virtual Stage Stage { get; set; }
    }
}
