//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhoAmI_PC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stage
    {
        public Stage()
        {
            this.answers = new HashSet<answer>();
            this.Characters = new HashSet<Character>();
            this.Criticals = new HashSet<Critical>();
            this.journals = new HashSet<journal>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public Nullable<int> idLevels { get; set; }
    
        public virtual ICollection<answer> answers { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Critical> Criticals { get; set; }
        public virtual ICollection<journal> journals { get; set; }
        public virtual Level Level { get; set; }
    }
}
